# Exercício:

## 01 – Obtenha os resultados e retorne o código em Python dos seguintes cálculos:

In [10]:
a = 2.0 + 3.0/5.0

b = (a + 10.2) - 5.0 * 2.0

c = a/b + 33.8

d = a/(b+c)

e = d*2

print (a, b, c, d, e)

2.6 2.799999999999999 34.72857142857143 0.0692805481537876 0.1385610963075752

## 02 – Obtenha os resultados e retorne o código em Python dos seguintes cálculos:

In [21]:
#a = [2.0, 3.0, 5.0] + [10,20,30]

#b = a *2

#c = a + b

# d = a/ (b*c) # TypeError: unsupported operand type(s) for /: 'list' and 'list' 

import numpy as np

a = np.array([2.0, 3.0, 5.0]) + np.array([10,20,30])
b = a *2
c = a + b   
d = a/ (b*c) 

print (a, b, c, d)

[12. 23. 35.] [24. 46. 70.] [ 36.  69. 105.] [0.01388889 0.00724638 0.0047619 ]

## 03 – Usando os objetos simples obtidos no exercício 01, instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [35]:
lista1 = [2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752] 
lista2 = [x**0.5 for x in lista1]
lista3 = lista1 + lista2
print (lista1)
print (lista2)  
print (lista3)

[2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752]
[1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]
[2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752, 1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [42]:
import numpy as np
lista4= lista3*2
array = np.array(lista4)
array = array.reshape(5,4)
print (array)

[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]]

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [45]:
medias = array.mean(axis=0)
medias_lista = medias.tolist()
medias_lista

[7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]

## 06 – O atributo shape pertence ao escopo dos objetos de classe numpy array. Ela retorna uma tupla onde o primeiro valor é o número de linhas e o segundo valor o de colunas contidas no array. Usando a informação do número total de valores presentes no numpy array do exercício 4 insira neste array a lista obtida no exercício 5. Recupere o array.
Obs.:  Atributos não usam () na chamada.

In [50]:
#array.shape
novo_array = np.concatenate((array, [medias_lista]), axis=0)
novo_array

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [66]:
import pandas as pd
novo_array.reshape(6,4) #já não tinha 4 colunas?

df_novo_array = pd.DataFrame(novo_array)
df_novo_array = df_novo_array.round(3)
df_novo_array

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [67]:
medias_linhas = df_novo_array.mean(axis=1)

df_novo_array['Média'] = medias_linhas
df_novo_array

        0      1       2      3     Média
0   2.600  2.800  34.729  0.069  10.04950
1   0.139  1.612   1.673  5.893   2.32925
2   0.263  0.372   2.600  2.800   1.50875
3  34.729  0.069   0.139  1.612   9.13725
4   1.673  5.893   0.263  0.372   2.05025
5   7.881  2.149   7.881  2.149   5.01500

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [ ]:
df_novo_array.describe()
print(df_novo_array.iloc[-1]) #média das colunas
print(df_novo_array["Média"]) #média das linhas

#a última linha e a última coluna são as médias, das colunas e das linhas.

0        7.881
1        2.149
2        7.881
3        2.149
Média    5.015
Name: 5, dtype: float64
0    10.04950
1     2.32925
2     1.50875
3     9.13725
4     2.05025
5     5.01500
Name: Média, dtype: float64

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [75]:
df_novo_array.columns = ['Coluna1', 'Coluna2', 'Coluna3', 'Coluna4', 'Média']
df_novo_array.index = ['Linha1', 'Linha2', 'Linha3', 'Linha4', 'Linha5', 'Média']
df_novo_array

media_das_medias = df_novo_array['Média'].mean()
print (media_das_medias)

5.015000000000001

In [76]:
df_novo_array.to_csv('resultados.csv')